# 1. ENTREE : Logstash écoute les agents Filebeat du réseau virtuel
input {
  beats {
    port => 5044
  }
}

# 2. FILTRES : Extraction et enrichissement des données selon la source
filter {
  # Si le log provient de la VM Suricata, on parse le JSON natif d'eve.json
  if [log][file][path] =~ "suricata" or [event][module] == "suricata" {
    json {
      source => "message"
      target => "suricata"
    }
  }
  
  # Si c'est un log Linux classique (syslog/auth.log), on peut appliquer un Grok standard
  else if [log][file][path] =~ "syslog" {
    grok {
      match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" }
    }
    date {
      match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
      target => "@timestamp"
    }
  }
}

# 3. SORTIE : Envoi sécurisé des flux vers la base Elasticsearch
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    
    # Création dynamique des index par type de log et par date
    if [log][file][path] =~ "suricata" {
      index => "logs-suricata-%{+YYYY.MM.dd}"
    } else {
      index => "logs-sys-%{+YYYY.MM.dd}"
    }
    
    # Obligatoire pour éviter l'erreur d'indexation dans les Data Streams Elastic 8.x
    action => "create"
  }
}